const hostUrl = "http://192.168.8.118:8080/"
export const pushTokenUrl = hostUrl+"ExpoPushTokenView/"
export const messageUrl = hostUrl+"MessageView/"
export const personalUrl = hostUrl+"PersonalView/"
export const roomUrl = hostUrl+"RoomView/"
export const loginUrl = hostUrl+"rest-auth/facebook/"
export const reportsUrl = hostUrl+"ReportsView/"
export const getRoomsUserIsIn = hostUrl+"/" +"/" /**remove ? */
export const matchUrl = hostUrl+"MatchesView/" 
export const imageUrl = hostUrl+"ImagesView/"
//send method: "GET"
export const logoutUrl = hostUrl + "rest-auth/logout/"
//send method: "DELETE"
export const deleteUrl = hostUrl + "rest-auth/logout/"
export const legalUrl = hostUrl +"LegalView/"
